### ISSUE TITLE
Use without npm / webpack

### ISSUE THREAD

**Issue by rightwayround** [crispinanderson/text-in-shape#3]
Hello, great project, thanks.

Is there any way of using this without requiring any dependencies other than build/index.js?

**Comment by crispinanderson** [comment]
Hi, sorry for my slow response. build/index.js is itself a module so it is designed to be imported into another module. However if you simply want a global textInShape you could just change the final export of the build/index.js

from:
module.exports = e })();

to:
window.textInShape = e })();
